name: Build and Deploy Jekyll (docs folder)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# These permissions allow the deploy-pages action to use OIDC and write to Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # 1) BUILD JOB
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build site
        run: |
          cd docs
          bundle exec jekyll build --source . --destination ../_site

  # 2) DEPLOY JOB
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
