name: Build and Deploy Jekyll

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # 1) Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build site
        run: |
          cd docs
          # Build Jekyll output into ../_site
          bundle exec jekyll build

      # IMPORTANT:
      # Use 'actions/upload-pages-artifact@v1' (not 'upload-artifact@v3').
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site   # The compiled site folder
          name: github-pages

  # 2) Deploy job
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # 'artifact_name' defaults to 'github-pages', so no need to specify if you kept name: github-pages
        # with:
        #   artifact_name: github-pages
